import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { FaqAccordion } from "@/components/faq-accordion";
import { Footer, Header } from "@/components/site-shell";
import { blogPosts, passportFaqs } from "@/content/blog";
import { getMessages, siteUrl } from "@/lib/i18n";

const post=blogPosts[0];
const title="U.S. Passport Photo Requirements: Size, Smile & Rules | PixEasy";
const description="U.S. passport photo rules explained: 2×2 size, head position, smile, ears, hair, glasses, clothing, background, and digital photo requirements.";
const canonical="/blog/us-passport-photo-requirements";
const articleUrl=`${siteUrl}${canonical}`;
export const metadata:Metadata={title:{absolute:title},description,alternates:{canonical},openGraph:{type:"article",siteName:"PixEasy",title,description,url:canonical,publishedTime:"2026-08-15",modifiedTime:"2026-08-15",authors:["PixEasy Editorial Team"],images:[{url:post.image,width:1536,height:1024,alt:post.imageAlt}]},twitter:{card:"summary_large_image",title,description,images:[post.image]}};

const requirements=[["Photo size","2 × 2 inches (51 × 51 mm)"],["Head size","1–1⅜ inches (25–35 mm), chin to top of head"],["Age","Taken within the last 6 months"],["Color","A clear color photo"],["Pose","Face the camera directly with eyes open"],["Background","Plain white or off-white"]];

export default function PassportPhotoGuidePage(){const messages=getMessages("en");const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:post.title,description,image:`${siteUrl}${post.image}`,datePublished:"2026-08-15",dateModified:"2026-08-15",inLanguage:"en-US",mainEntityOfPage:articleUrl,author:{"@type":"Organization",name:"PixEasy Editorial Team",url:siteUrl},publisher:{"@type":"Organization",name:"PixEasy",url:siteUrl,logo:{"@type":"ImageObject",url:`${siteUrl}/apple-touch-icon.png`}}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"PixEasy",item:`${siteUrl}/`},{"@type":"ListItem",position:2,name:"Blog",item:`${siteUrl}/blog`},{"@type":"ListItem",position:3,name:post.title,item:articleUrl}]},{"@type":"FAQPage",mainEntity:passportFaqs.map((item)=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}]};return <><Header locale="en" messages={messages}/><main className="wrap article-main"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/blog">Blog</Link><span aria-hidden="true">/</span><span>U.S. passport photos</span></nav><article>
<header className="article-header"><p className="eyebrow">Passport photo guide</p><h1>U.S. Passport Photo Requirements: Size, Smile &amp; Rules</h1><p className="article-deck">A practical guide to the current State Department rules for printed and digital U.S. passport photos.</p><p className="article-byline">By PixEasy Editorial Team · Published August 15, 2026 · Last reviewed August 2026</p></header>
<aside className="article-note" aria-label="Important note"><strong>Check before you apply.</strong> Requirements can change, and special cases may need supporting documents. Always confirm the latest rules on the official U.S. State Department website.</aside>
<section className="quick-facts" aria-labelledby="quick-facts-title"><h2 id="quick-facts-title">U.S. passport photo requirements at a glance</h2><dl>{requirements.map(([term,detail])=><div key={term}><dt>{term}</dt><dd>{detail}</dd></div>)}</dl></section>
<section><h2>Size and head position</h2><p>A printed photo must be exactly <strong>2 × 2 inches (51 × 51 mm)</strong>. From the bottom of your chin to the top of your head, the measurement must be <strong>1 to 1⅜ inches (25 to 35 mm)</strong>. Center your head, show it fully, and look directly into the camera.</p><p>Hair may extend toward the edge of the photo as long as the full head remains visible and the required head measurement is correct. Before printing, use the <Link href="/image-size-calculator">Image Size Calculator</Link> to translate inches or millimeters into pixels at your printer’s PPI.</p></section>
<section><h2>Expression, ears, hair, and bangs</h2><div className="article-rule-grid"><article><h3>Can you smile?</h3><p>Yes—a natural smile is acceptable when your mouth is closed and both eyes are open. A neutral expression also works. Avoid a wide smile, open mouth, or exaggerated expression.</p></article><article><h3>Do your ears need to show?</h3><p>No. The published passport rules do not require both ears to be visible. What matters is that your full face is clear and you face the camera directly.</p></article><article><h3>Can bangs cover your eyebrows?</h3><p>The rules do not specifically require visible eyebrows. However, hair must not cover your eyes or obscure any part of your face. Move long bangs if they create shadows or hide an eye.</p></article></div></section>
<section><h2>Glasses, hats, clothing, and accessories</h2><p>Remove eyeglasses, sunglasses, and tinted glasses. A rare medical exception requires a signed statement from a medical professional. Hats and head coverings are generally not allowed; religious or medical exceptions require a signed statement, and the covering cannot hide your face or cast shadows.</p><p>Do not wear a uniform, uniform-like clothing, or camouflage. Everyday clothing is appropriate. Jewelry and facial piercings are allowed when they do not hide your face.</p></section>
<section><h2>Background and lighting</h2><p>Use a plain white or off-white background without patterns, visible objects, textures, or shadows. Light your face evenly from the front. Avoid harsh side lighting, overexposure, underexposure, red-eye, and background shadows.</p></section>
<figure className="passport-example"><Image src={post.image} alt={post.imageAlt} width={1536} height={1024} priority sizes="(max-width: 900px) 100vw, 840px"/><figcaption><strong>Acceptable and common unacceptable examples.</strong> This graphic is an educational illustration, not an official government sample. The portraits are AI-generated and must not be submitted with a passport application.</figcaption></figure>
<section><h2>Printed photo vs. online renewal upload</h2><div className="comparison-table" role="table" aria-label="Printed and online passport photo requirements"><div role="row"><strong role="columnheader">Printed application</strong><strong role="columnheader">Online renewal</strong></div><div role="row"><span role="cell">2 × 2 inches (51 × 51 mm)</span><span role="cell">JPG, JPEG, PNG, HEIC, or HEIF</span></div><div role="row"><span role="cell">Head: 1–1⅜ inches (25–35 mm)</span><span role="cell">54 KB to 10 MB</span></div><div role="row"><span role="cell">Printed in color on photo-quality paper</span><span role="cell">Color photo; reposition and crop in the upload tool</span></div></div><p>The online tool checks basic technical requirements, but passing that check does not guarantee acceptance. A passport employee still reviews the photo.</p></section>
<section className="editing-warning"><h2>Do not digitally alter your appearance</h2><p>Do not use retouching, beauty filters, background replacement, generative AI, or editing tools to change facial features, skin texture, hair, the outline of your head, or the background. Cropping and resizing are appropriate only when the original photo itself remains unchanged.</p></section>
<aside className="article-cta"><div><p className="eyebrow">Free browser tool</p><h2>Calculate the exact print size</h2><p>Convert 2 inches or 51 mm into pixels at your chosen PPI. Nothing is uploaded to a server.</p></div><Link className="primary-btn" href="/image-size-calculator">Open Image Size Calculator</Link></aside>
<section><h2>Frequently asked questions</h2><FaqAccordion items={[...passportFaqs]}/></section>
<section><h2>Official sources</h2><p>This guide summarizes the U.S. Department of State’s current instructions. For authoritative details and updates, visit:</p><ul className="official-links"><li><a href="https://travel.state.gov/en/passports/apply/help/photos.html" rel="noopener noreferrer">U.S. Department of State: Passport Photos</a></li><li><a href="https://travel.state.gov/en/passports/renew-replace/online/upload-digital-photo.html" rel="noopener noreferrer">U.S. Department of State: Uploading a Digital Photo</a></li></ul></section>
<section><h2>Related PixEasy tools</h2><nav className="related-tool-grid" aria-label="Related image tools"><Link href="/image-size-calculator"><strong>Image Size Calculator</strong><span>Convert inches, millimeters, and pixels using PPI.</span></Link><Link href="/resize-image"><strong>Resize Image</strong><span>Resize an image in your browser without uploading it.</span></Link></nav></section>
</article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/></main><Footer locale="en" messages={messages}/></>}
