import type { ToolKind } from "@/components/image-tool";
import type { Locale } from "@/lib/i18n";

export type PixelateContent={title:string;seoTitle:string;seoDescription:string;description:string;cardDescription:string;ui:Record<string,string>;useCases:string[];steps:string[];practical:{heading:string;body:string}[];faqs:{question:string;answer:string}[];related:ToolKind[]};

export const pixelateContent:Record<Locale,PixelateContent>={
  en:{
    title:"Pixelate Image",seoTitle:"Pixelate Image Online - Create Pixel Art Style | PixEasy",seoDescription:"Pixelate images online. Adjust pixel size and colors, preview instantly, and download without server uploads.",cardDescription:"Turn images into a pixelated style.",
    description:"Turn photos and images into a pixelated style directly in your browser. Adjust pixel size and colors, preview the result instantly, and download without uploading your image to a server.",
    ui:{preview:"Preview",original:"Original",result:"Pixelated",pixelArtResult:"Pixel Art",reset:"Reset",options:"Pixelation settings",style:"Style",pixelated:"Pixelated",pixelArt:"Pixel Art",pixelatedDescription:"Creates large pixel blocks.",pixelArtDescription:"Reduces colors for a retro game-style look.",dithering:"Dithering",pixelSize:"Pixel Size",colors:"Colors",originalColors:"Original",colors32:"32 colors",colors16:"16 colors",colors8:"8 colors",outputSize:"Output Size",keepSize:"Keep original dimensions",actualSize:"Actual pixel dimensions",download:"Download PNG",processing:"Updating preview…",replace:"Replace image",output:"Output",privacy:"Your image stays in your browser.",useful:"When is this useful?",how:"How to use",practical:"Helpful information",faq:"Frequently asked questions",related:"Related tools"},
    useCases:["Pixelate a photo with large blocks for a mosaic-like effect.","Simplify a portrait or landscape into a limited palette for retro game artwork.","Turn a character or illustration into a crisp dot-style graphic.","Reduce colors and optionally add dithering for a classic game look.","Create a genuinely low-resolution pixel image for design work."],
    steps:["Upload a JPG, PNG, or WebP image.","Adjust Pixel Size to control the strength of the effect.","Optionally limit the number of colors.","Compare the original and pixelated previews.","Choose the output dimensions.","Download the result as a PNG."],
    practical:[{heading:"Pixel size",body:"Larger values create bigger blocks and a stronger pixel effect; smaller values preserve more detail."},{heading:"Color levels",body:"Reducing colors simplifies the image and can make it feel closer to classic game graphics."},{heading:"Two output sizes",body:"Keep original dimensions saves a nearest-neighbor enlarged result. Actual pixel dimensions saves the small internal canvas itself."},{heading:"Local processing",body:"PixEasy processes the image with Canvas in your browser. It is not generative AI, and the file is not uploaded to a server."}],
    faqs:[{question:"What is the difference between Pixelated and Pixel Art?",answer:"Pixelated creates large image blocks. Pixel Art also reduces the number of colors and builds a representative palette for a look closer to retro game graphics."},{question:"Can I make a photo look like a pixel-art game character?",answer:"PixEasy simplifies the photo's resolution and colors into a pixel-art style. It does not redraw faces or objects like generative AI, so it keeps the original form while adding a dot-graphic look."},{question:"What does Pixel Size mean?",answer:"It controls the strength of the effect. A larger value produces larger square pixels and a simpler image."},{question:"What changes when I reduce the number of colors?",answer:"The image uses a smaller color palette, creating clearer color regions that feel closer to retro game graphics."},{question:"What does dithering do?",answer:"Dithering uses small dot patterns to suggest tones between limited palette colors. It can add a classic game look, but may appear grainy on portraits."},{question:"Is my image uploaded to a server?",answer:"No. Image decoding, pixelation, previewing, and download creation all happen in your browser."},{question:"Can I save a truly low-resolution image?",answer:"Yes. Choose Actual pixel dimensions to download the small resolution used during pixelation."},{question:"Can I use JPG and PNG images?",answer:"Yes. You can upload JPG, JPEG, PNG, and WebP images. The result downloads as PNG by default."}],related:["resize","compress","invert","jpg-png","png-jpg"]
  },
  ko:{
    title:"이미지 픽셀화",seoTitle:"이미지 픽셀화 - 사진 픽셀아트·도트 이미지 만들기 | PixEasy",seoDescription:"사진과 이미지를 픽셀아트·도트 스타일로 변환하세요. 픽셀 크기와 색상 수를 조절하고 서버 업로드 없이 다운로드할 수 있습니다.",cardDescription:"사진과 이미지를 픽셀아트 느낌으로 변환합니다.",
    description:"사진이나 이미지를 간단하게 픽셀아트 느낌으로 변환하세요. 픽셀 크기와 색상 수를 조절하고 결과를 바로 확인한 뒤 서버 업로드 없이 다운로드할 수 있습니다.",
    ui:{preview:"미리보기",original:"원본",result:"픽셀화",pixelArtResult:"픽셀아트",reset:"초기화",options:"픽셀화 설정",style:"스타일",pixelated:"픽셀화",pixelArt:"픽셀아트",pixelatedDescription:"이미지를 큰 픽셀 단위로 표현합니다.",pixelArtDescription:"색상을 단순화해 레트로 게임 같은 도트 느낌을 만듭니다.",dithering:"디더링",pixelSize:"픽셀 크기",colors:"색상 수",originalColors:"원본 색상",colors32:"32색",colors16:"16색",colors8:"8색",outputSize:"출력 크기",keepSize:"원본 크기 유지",actualSize:"실제 픽셀 크기로 저장",download:"PNG 다운로드",processing:"미리보기 업데이트 중…",replace:"이미지 교체",output:"결과",privacy:"이미지는 브라우저에서만 처리됩니다.",useful:"이럴 때 유용합니다",how:"사용 방법",practical:"알아두면 좋은 정보",faq:"자주 묻는 질문",related:"관련 도구"},
    useCases:["사진을 큰 픽셀로 나눠 모자이크 같은 픽셀화 효과를 만들 때","인물이나 풍경 사진의 색상을 단순화해 픽셀아트로 만들 때","캐릭터나 일러스트를 선명한 도트 이미지처럼 표현할 때","제한된 색상과 디더링으로 레트로 게임 스타일 이미지를 만들 때","실제 저해상도 도트 이미지를 디자인 작업에 활용할 때"],
    steps:["JPG, PNG 또는 WebP 이미지를 업로드합니다.","픽셀 크기를 조절합니다.","필요한 경우 색상 수를 줄입니다.","원본과 결과 미리보기를 비교합니다.","원하는 출력 크기를 선택합니다.","PNG 파일로 다운로드합니다."],
    practical:[{heading:"픽셀 크기",body:"값이 클수록 사각형 픽셀이 커지고 효과가 강해지며, 값이 작을수록 원본 디테일이 더 많이 남습니다."},{heading:"색상 수",body:"색상 수를 줄이면 이미지가 단순해져 레트로 게임 그래픽에 가까운 느낌을 만들 수 있습니다."},{heading:"두 가지 출력 크기",body:"원본 크기 유지는 선명한 픽셀 경계를 유지한 채 원본 해상도로 저장합니다. 실제 픽셀 크기는 처리에 사용한 저해상도 자체로 저장합니다."},{heading:"브라우저 로컬 처리",body:"Canvas로 브라우저에서만 처리합니다. 새로운 그림을 생성하는 AI 기능이 아니며 파일을 서버로 업로드하지 않습니다."}],
    faqs:[{question:"픽셀화와 픽셀아트의 차이는 무엇인가요?",answer:"픽셀화는 이미지를 큰 픽셀 단위로 표현하는 효과입니다. 픽셀아트 모드는 여기에 색상 수를 줄이고 대표 팔레트를 구성하여 레트로 게임 그래픽과 비슷한 느낌을 만듭니다."},{question:"사진을 게임 캐릭터 같은 픽셀아트로 만들 수 있나요?",answer:"PixEasy는 사진의 해상도와 색상을 단순화하여 픽셀아트 스타일로 변환합니다. 생성형 AI처럼 얼굴이나 사물을 새롭게 그리는 기능은 아니므로 원본 형태를 유지하면서 도트 느낌을 만드는 데 적합합니다."},{question:"픽셀 크기는 무엇인가요?",answer:"픽셀 효과의 강도를 조절하는 값입니다. 값이 커질수록 큰 사각형 픽셀이 나타나고 이미지가 더 단순해집니다."},{question:"색상 수를 줄이면 어떤 차이가 있나요?",answer:"이미지에서 사용하는 색상을 대표 팔레트로 제한하여 색상 영역이 명확하고 레트로 게임 그래픽에 가까운 느낌을 만들 수 있습니다."},{question:"디더링은 어떤 기능인가요?",answer:"제한된 팔레트의 색상 사이를 작은 점 패턴으로 표현합니다. 클래식 게임 같은 느낌을 더하지만 인물 사진에서는 다소 거칠게 보일 수 있습니다."},{question:"이미지가 서버에 업로드되나요?",answer:"아니요. 이미지 처리는 브라우저에서 이루어지며 파일은 PixEasy 서버에 업로드하거나 저장하지 않습니다."},{question:"실제 저해상도 이미지로 저장할 수 있나요?",answer:"네. 출력 크기에서 실제 픽셀 크기로 저장을 선택하면 픽셀화 과정에서 사용된 낮은 해상도로 다운로드할 수 있습니다."},{question:"JPG와 PNG 모두 사용할 수 있나요?",answer:"JPG, JPEG, PNG, WebP 등의 일반적인 이미지 파일을 업로드할 수 있습니다. 결과는 기본적으로 PNG로 다운로드할 수 있습니다."}],related:["resize","compress","invert","jpg-png","png-jpg"]
  },
  ja:{
    title:"画像をピクセル化",seoTitle:"画像をピクセル化 - 写真をドット絵風に変換 | PixEasy",seoDescription:"写真や画像を無料でピクセル・ドット絵風に変換。ピクセルサイズや色数を調整し、サーバーへ送信せずダウンロードできます。",cardDescription:"画像をピクセル風に変換します。",
    description:"写真や画像を簡単にピクセル風に変換できます。ピクセルサイズや色数を調整し、ブラウザ上で結果を確認してそのままダウンロードできます。",
    ui:{preview:"プレビュー",original:"元画像",result:"ピクセル化",pixelArtResult:"ピクセルアート",reset:"リセット",options:"ピクセル化設定",style:"スタイル",pixelated:"ピクセル化",pixelArt:"ピクセルアート",pixelatedDescription:"画像を大きなピクセル単位で表現します。",pixelArtDescription:"色数を減らしてレトロゲーム風のドット表現にします。",dithering:"ディザリング",pixelSize:"ピクセルサイズ",colors:"色数",originalColors:"元の色",colors32:"32色",colors16:"16色",colors8:"8色",outputSize:"出力サイズ",keepSize:"元のサイズを維持",actualSize:"実際のピクセルサイズで保存",download:"PNGをダウンロード",processing:"プレビューを更新中…",replace:"画像を変更",output:"出力",privacy:"画像はブラウザ内で処理されます。",useful:"こんなときに便利です",how:"使い方",practical:"知っておきたいこと",faq:"よくある質問",related:"関連ツール"},
    useCases:["写真を大きなピクセルでモザイク風に加工したいとき","人物や風景の色を単純化してピクセルアート風にしたいとき","キャラクターやイラストをくっきりしたドット画像にしたいとき","限られた色とディザリングでレトロゲーム風にしたいとき","デザイン用の低解像度画像を作りたいとき"],
    steps:["JPG、PNG、WebP画像をアップロードします。","ピクセルサイズを調整します。","必要に応じて色数を減らします。","元画像と結果を比較します。","出力サイズを選びます。","PNGでダウンロードします。"],
    practical:[{heading:"ピクセルサイズ",body:"値が大きいほど四角いピクセルが大きくなり、強い効果になります。小さい値では細部が多く残ります。"},{heading:"色数",body:"色数を減らすと画像が単純化され、レトロゲームのグラフィックに近い印象になります。"},{heading:"2種類の出力",body:"元のサイズを維持すると輪郭をぼかさず元の解像度で保存できます。実際のピクセルサイズでは処理に使った低解像度で保存します。"},{heading:"ブラウザ内処理",body:"Canvasを使ってブラウザ内だけで処理します。生成AIではなく、画像をサーバーへ送信しません。"}],
    faqs:[{question:"ピクセル化とピクセルアートの違いは何ですか？",answer:"ピクセル化は画像を大きなピクセル単位で表現する効果です。ピクセルアートはさらに色数を減らし、代表パレットを作ってレトロゲーム風の表現にします。"},{question:"写真をゲームキャラクター風のピクセルアートにできますか？",answer:"PixEasyは写真の解像度と色を単純化してピクセルアート風に変換します。生成AIのように顔や物を描き直す機能ではないため、元の形を保ちながらドット感を加える用途に適しています。"},{question:"ピクセルサイズとは何ですか？",answer:"効果の強さを調整する値です。大きくするほど四角いピクセルが大きくなり、画像が単純になります。"},{question:"色数を減らすとどう変わりますか？",answer:"使用する色を代表パレットに制限し、色の領域が明確なレトロゲーム風の印象を作れます。"},{question:"ディザリングとは何ですか？",answer:"限られたパレットの中間色を細かな点のパターンで表現します。クラシックゲーム風になりますが、人物写真では粗く見える場合があります。"},{question:"画像はサーバーへ送信されますか？",answer:"いいえ。画像の処理はブラウザ内で行われ、PixEasyのサーバーへ送信・保存されません。"},{question:"実際の低解像度で保存できますか？",answer:"はい。出力サイズで実際のピクセルサイズを選ぶと、ピクセル化に使った低解像度でダウンロードできます。"},{question:"JPGとPNGの両方を使えますか？",answer:"JPG、JPEG、PNG、WebPをアップロードできます。結果は標準でPNGとしてダウンロードできます。"}],related:["resize","compress","invert","jpg-png","png-jpg"]
  }
};
